version: 0.2
env: 
  parameter-store: 
    REACT_APP_ACCESS_KEY_ID: "REACT_APP_ACCESS_KEY_ID"
    REACT_APP_SECRET_ACCESS_KEY: "REACT_APP_SECRET_ACCESS_KEY"
    REACT_APP_REGION_ID: "REACT_APP_REGION_ID"
    REACT_APP_BUCKET_NAME: "REACT_APP_BUCKET_NAME"

phases: 
  pre_build: 
    commands:
      - npm install 
  build:
    commands: 
      - npm run build
  
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
  